CONNECT SYS/admin AS SYSDBA;
ALTER SYSTEM SET DB_CREATE_FILE_DEST = '/vagrant/db';
 
ALTER PROFILE DEFAULT LIMIT
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_LIFE_TIME UNLIMITED;
 
Exec DBMS_XDB.SETHTTPPORT(8087);